name: Github Actions Trial Run
on:
  push
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install npm stuff
        run: npm install
      - name: Check what we have
        run: ls -l
      - name: Run tests
        run: npm run test
      - name: Build the code
        run: npm run build
      - name: Check what we have
        run: ls -l dist/
