name: Github Actions Trial Run
on:
  push
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: See what we have
        run: ls -l
      - name: Install npm stuff
        run: npm install
