name: Github Actions Trial Run
on:
  push
jobs:
  explore-actions:
    runs-on: ubuntu-latest
    steps:
      - name: "Say Hello"
        run: echo "hello world"
      - name: "where am I?"
        run: pwd
      - name: "Where is the workspace?"
        run: echo "${{ github.workspace }}"
